### ISSUE TITLE
flakiness report not working

### ISSUE THREAD

**Issue by asos-paulmacdonald** [shazam/fork#113]
Hello again,

Can you point me in the right direction to solve this issue pls?: 

`Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:494)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.<init>(JenkinsHttpClient.java:96)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.<init>(JenkinsHttpClient.java:106)
	at com.offbytwo.jenkins.JenkinsServer.<init>(JenkinsServer.java:58)
	at com.shazam.fork.reporter.gradle.JenkinsDownloader.getJenkinsServer(JenkinsDownloader.java:70)
	at com.shazam.fork.reporter.gradle.JenkinsDownloader.downloadJenkinsFiles(JenkinsDownloader.java:43)
	at com.shazam.fork.reporter.gradle.ForkJenkinsReportTask.runForkJenkins(ForkJenkinsReportTask.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more

`

**Comment by iordanis** [comment]
Have you been able to work around this? Did you figure out what's wrong?

I can only think of authentication as a potential issue. Some sample code will help.

**Comment by asos-savvasdalkitsis** [comment]
The error happens because `com.android.tools.build:gradle:3.0.1` is bringing in older versions of `org.apache.httpcomponents:httpcore` and `org.apache.httpcomponents:httclient`.

Fork reporter is bringing in `com.offbytwo.jenkins:jenkins-client` which in turn brings in the above two httcomponents version 4.3.3 and 4.3.6. The old version brought in by the android gradle build tools is missing two static fields:

`BasicLineFormatter.INSTANCE` and `SystemDefaultDnsResolver.INSTANCE` that jenkins-client is relying on.

A temporary solution until the gradle build tools update their versions of the httpcomponents is to add this to your buildscript:

```
classpath("com.android.tools.build:gradle:3.0.1") {
            exclude group: 'org.apache.httpcomponents', module: 'httpcore'
            exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        }
        classpath 'org.apache.httpcomponents:httpcore:4.3.3'
        classpath 'org.apache.httpcomponents:httpclient:4.3.6'
```
