### ISSUE TITLE
NumberFormatException: For input string: "Unspecified API Level"

### ISSUE THREAD

**Issue by yogurtearl** [shazam/fork#2]
This is an intermittent error ( it worked when I just re-ran it ). 
It might have been an ADB hiccup.

```
Use -Dfork.report.subtitle=Subitle to specify a subtitle for the generated report
Error while Fork runner was executing
java.lang.NumberFormatException: For input string: "Unspecified API Level"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.shazam.fork.pooling.PoolByApi.getParameter(PoolByApi.java:29)
	at com.shazam.fork.pooling.SmallestComputedPoolsSelector.poolForDevice(SmallestComputedPoolsSelector.java:37)
	at com.shazam.fork.pooling.ComputedDevicePoolLoader.createComputedPools(ComputedDevicePoolLoader.java:53)
	at com.shazam.fork.pooling.ComputedDevicePoolLoader.loadPools(ComputedDevicePoolLoader.java:45)
	at com.shazam.fork.pooling.CompositeDevicePoolLoader.loadPools(CompositeDevicePoolLoader.java:38)
	at com.shazam.fork.ForkRunner.run(ForkRunner.java:76)
	at com.shazam.fork.Fork.run(Fork.java:46)
	at com.shazam.fork.Fork$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.shazam.fork.gradle.ForkRunTask.runFork(ForkRunTask.groovy:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
```

**Comment by iordanis** [comment]
Fixed in earlier version
